Repository kuzzleio/sdk-go, pull requests merged in 2018-07, with the labels that each got.

#171 fix return value for document controller
  document/create.go
  document/createOrReplace.go
  document/delete.go
  document/mCreate.go
  document/mCreateOrReplace.go
  document/mGet.go
  document/mReplace.go
  document/mUpdate.go
  document/replace.go
  document/update.go
  internal/wrappers/cgo/kuzzle/document.go
Labels: changelog:breaking-changes

#175 embed .so file in .jar file
  internal/wrappers/Makefile
Labels: changelog:bug-fixes

#170 Add document test
  internal/wrappers/features/run_cpp.sh
  internal/wrappers/features/step_defs_cpp/collection-steps.cpp
  internal/wrappers/features/step_defs_cpp/document-steps.cpp
  internal/wrappers/features/step_defs_cpp/kuzzle-sdk-steps.cpp
  internal/wrappers/features/step_defs_cpp/realtime-steps.cpp
  internal/wrappers/features/step_defs_cpp/steps.hpp
Labels: changelog:exclude

#179 Rename struct members for java getter/setter
  internal/wrappers/templates/java/core.i
Labels: changelog:bug-fixes

#180 Change options.offline_mode type
  internal/wrappers/cgo/kuzzle/options.go
  internal/wrappers/headers/kuzzlesdk.h
Labels: changelog:enhancements

#182 Rename deprecated method ReplayQueue to PlayQueue
  .codepipeline/builds/amd64.yml
  .codepipeline/builds/armv7.yml
  .codepipeline/builds/i386.yml
  .codepipeline/deploys/amd64.yml
  .codepipeline/deploys/i386.yml
  .codepipeline/tests/amd64.yml
  .codepipeline/tests/i386.yml
  .travis.yml
  README.md
  connection/connection.go
  connection/websocket/web_socket.go
  internal/mock_connection.go
  internal/wrappers/README.md
  internal/wrappers/cgo/kuzzle/kuzzle.go
  internal/wrappers/cpp/kuzzle.cpp
  internal/wrappers/headers/kuzzle.hpp
  internal/wrappers/templates/java/javadoc/kuzzle.i
  kuzzle/queue.go
Labels: changelog:enhancements
