Repository kuzzleio/sdk-go, pull requests merged in 2018-06, with the labels that each got.

#158 Kzl 70 cpp e2e tests
  .gitignore
  internal/wrappers/Makefile
  internal/wrappers/README.md
  internal/wrappers/build_cpp_test.sh
  internal/wrappers/cgo/kuzzle/auth.go
  internal/wrappers/cgo/kuzzle/destructors.go
  internal/wrappers/cpp/auth.cpp
  internal/wrappers/cpp/index.cpp
  internal/wrappers/cpp/server.cpp
  internal/wrappers/features/auth.feature
  internal/wrappers/features/documents.feature
  internal/wrappers/features/fixtures/run.sh
  internal/wrappers/features/sdks.feature
  internal/wrappers/features/step_definitions/cucumber.wire
  internal/wrappers/features/step_defs_cpp/3rdparty/json_spirit/CMakeLists.txt
  internal/wrappers/features/step_defs_cpp/3rdparty/json_spirit/json_spirit.h
  internal/wrappers/features/step_defs_cpp/3rdparty/json_spirit/json_spirit.vcproj
  internal/wrappers/features/step_defs_cpp/3rdparty/json_spirit/json_spirit_error_position.h
  internal/wrappers/features/step_defs_cpp/3rdparty/json_spirit/json_spirit_reader.cpp
  internal/wrappers/features/step_defs_cpp/3rdparty/json_spirit/json_spirit_reader.h
  internal/wrappers/features/step_defs_cpp/3rdparty/json_spirit/json_spirit_reader_template.h
  internal/wrappers/features/step_defs_cpp/3rdparty/json_spirit/json_spirit_stream_reader.h
  internal/wrappers/features/step_defs_cpp/3rdparty/json_spirit/json_spirit_utils.h
  internal/wrappers/features/step_defs_cpp/3rdparty/json_spirit/json_spirit_value.cpp
  internal/wrappers/features/step_defs_cpp/3rdparty/json_spirit/json_spirit_value.h
  internal/wrappers/features/step_defs_cpp/3rdparty/json_spirit/json_spirit_writer.cpp
  internal/wrappers/features/step_defs_cpp/3rdparty/json_spirit/json_spirit_writer.h
  internal/wrappers/features/step_defs_cpp/3rdparty/json_spirit/json_spirit_writer_template.h
  internal/wrappers/features/step_defs_cpp/CMakeLists.txt
  internal/wrappers/features/step_defs_cpp/kuzzle-sdk-steps.cpp
  internal/wrappers/features/step_defs_cpp/kuzzle_utils.cpp
  internal/wrappers/features/step_defs_cpp/kuzzle_utils.h
  internal/wrappers/headers/auth.hpp
  internal/wrappers/headers/collection.hpp
  internal/wrappers/headers/event_emitter.hpp
  internal/wrappers/headers/exceptions.hpp
  internal/wrappers/headers/index.hpp
  internal/wrappers/headers/kuzzlesdk.h
  internal/wrappers/headers/realtime.hpp
Labels: changelog:bug-fixes

#156 Generate Python SDK
  .github/issue_template.md
  .github/pull_request_template.md
  .travis.yml
  README.md
  internal/wrappers/Makefile
  internal/wrappers/cgo/kuzzle/destructors.go
  internal/wrappers/cgo/kuzzle/go_to_c.go
  internal/wrappers/cgo/kuzzle/realtime.go
  internal/wrappers/cpp/auth.cpp
  internal/wrappers/cpp/collection.cpp
  internal/wrappers/cpp/document.cpp
  internal/wrappers/cpp/index.cpp
  internal/wrappers/features/java/src/test/java/gradle/cucumber/Documentdefs.java
  internal/wrappers/features/java/src/test/java/gradle/cucumber/KuzzleSingleton.java
  internal/wrappers/features/java/src/test/java/gradle/cucumber/Logindefs.java
  internal/wrappers/features/java/src/test/java/gradle/cucumber/Subscribedefs.java
  internal/wrappers/features/java/src/test/java/gradle/cucumber/UserManagementdefs.java
  internal/wrappers/features/java/src/test/java/gradle/cucumber/World.java
  internal/wrappers/features/sdks.feature
  internal/wrappers/headers/kuzzle.hpp
  internal/wrappers/templates/python/core.i
  internal/wrappers/templates/python/setup.py
  internal/wrappers/templates/python/test.py
  kuzzle/query.go
  realtime/publish.go
  realtime/publish_test.go
Labels: blocked, changelog:new-features

#160 finalize e2e test
  README.md
  internal/wrappers/Makefile
  internal/wrappers/features/auth.feature
  internal/wrappers/features/documents.feature
  internal/wrappers/features/realtime.feature
  internal/wrappers/features/sdks.feature
Labels: changelog:exclude

#146 Launch Java SDK tests on CodePipeline
  .codepipeline/builds/amd64.yml
  .codepipeline/builds/armv7.yml
  .codepipeline/builds/i386.yml
  .codepipeline/deploys/amd64.yml
  .codepipeline/deploys/i386.yml
  .codepipeline/docker-compose.yml
  .codepipeline/start_kuzzle.sh
  .codepipeline/tests/amd64.yml
  .codepipeline/tests/golang.yml
  .codepipeline/tests/i386.yml
  .gitignore
  buildspec-build-java_amd64.yml
  buildspec-build-java_armv7.yml
  buildspec-build-java_i686.yml
  internal/wrappers/Makefile
  internal/wrappers/build_cpp_test.sh
  internal/wrappers/features/e2e.sh
  internal/wrappers/features/fixtures/run.sh
  internal/wrappers/features/run_cpp.sh
  internal/wrappers/features/run_java.sh
Labels: changelog:exclude, wip

#161 Java e2e document controller
  document/count.go
  document/count_test.go
  document/get.go
  document/mDelete.go
  document/search.go
  internal/wrappers/cgo/kuzzle/auth.go
  internal/wrappers/cgo/kuzzle/c_to_go.go
  internal/wrappers/cgo/kuzzle/collection.go
  internal/wrappers/cgo/kuzzle/destructors.go
  internal/wrappers/cgo/kuzzle/document.go
  internal/wrappers/cgo/kuzzle/go_to_c.go
  internal/wrappers/cgo/kuzzle/index.go
  internal/wrappers/cgo/kuzzle/kuzzle.go
  internal/wrappers/cgo/kuzzle/realtime.go
  internal/wrappers/cgo/kuzzle/server.go
  internal/wrappers/cpp/collection.cpp
  internal/wrappers/cpp/document.cpp
  internal/wrappers/cpp/index.cpp
  internal/wrappers/cpp/realtime.cpp
  internal/wrappers/features/documents.feature
  internal/wrappers/features/java/src/test/java/gradle/cucumber/Documentdefs.java
  internal/wrappers/features/java/src/test/java/gradle/cucumber/Geofencedefs.java
  internal/wrappers/features/java/src/test/java/gradle/cucumber/Subscribedefs.java
  internal/wrappers/features/java/src/test/java/gradle/cucumber/UserManagementdefs.java
  internal/wrappers/features/realtime.feature
  internal/wrappers/headers/kuzzlesdk.h
  types/search_result.go
Labels: changelog:bug-fixes

#164 Fix C++ test execution
  README.md
  internal/wrappers/build_cpp_tests.sh
  internal/wrappers/features/e2e.sh
  internal/wrappers/features/run_cpp.sh
  internal/wrappers/features/step_defs_cpp/kuzzle-sdk-steps.cpp
Labels: changelog:exclude

#162 Java e2e index controller
  .travis.yml
  internal/wrappers/Makefile
  internal/wrappers/features/index.feature
  internal/wrappers/features/java/src/test/java/gradle/cucumber/Documentdefs.java
  internal/wrappers/features/java/src/test/java/gradle/cucumber/Indexdefs.java
  internal/wrappers/features/java/src/test/java/gradle/cucumber/Subscribedefs.java
  internal/wrappers/templates/java/core.i
  test.sh
Labels: changelog:bug-fixes

#163 Java e2e collection controller
  internal/wrappers/Makefile
  internal/wrappers/cgo/kuzzle/collection.go
  internal/wrappers/features/collection.feature
  internal/wrappers/features/java/src/test/java/gradle/cucumber/Collectiondefs.java
Labels: changelog:bug-fixes

#165 Update Cmake to compile every .cpp present in folder
  README.md
  internal/wrappers/features/collection.feature
  internal/wrappers/features/step_defs_cpp/CMakeLists.txt
  internal/wrappers/features/step_defs_cpp/steps.hpp
Labels: changelog:exclude

#168 e2e test of realtime controller in cpp sdk
  internal/wrappers/cpp/realtime.cpp
  internal/wrappers/features/java/src/test/java/gradle/cucumber/Subscribedefs.java
  internal/wrappers/features/realtime.feature
  internal/wrappers/features/step_defs_cpp/kuzzle-sdk-steps.cpp
  internal/wrappers/features/step_defs_cpp/kuzzle_utils.h
  internal/wrappers/features/step_defs_cpp/realtime-steps.cpp
  internal/wrappers/features/step_defs_cpp/steps.hpp
  internal/wrappers/headers/sdk_wrappers_internal.h
Labels: changelog:exclude

#167 KZL-114 : [C++] Index controller tests
  .gitignore
  internal/wrappers/Makefile
  internal/wrappers/features/index.feature
  internal/wrappers/features/step_defs_cpp/index-steps.cpp
  internal/wrappers/features/step_defs_cpp/kuzzle-sdk-steps.cpp
  internal/wrappers/features/step_defs_cpp/kuzzle_utils.h
Labels: changelog:exclude

#169 Add collection tests
  .github/pull_request_template.md
  internal/wrappers/README.md
  internal/wrappers/features/collection.feature
  internal/wrappers/features/run_cpp.sh
  internal/wrappers/features/step_defs_cpp/collection-steps.cpp
  internal/wrappers/features/step_defs_cpp/kuzzle-sdk-steps.cpp
  internal/wrappers/features/step_defs_cpp/kuzzle_utils.cpp
  internal/wrappers/features/step_defs_cpp/realtime-steps.cpp
  internal/wrappers/features/step_defs_cpp/steps.hpp
Labels: changelog:exclude
