Repository kuzzleio/sdk-go, pull requests merged in 2018-03, with the labels that each got.

#132 Fix memleaks
  internal/wrappers/cpp/collection.cpp
  internal/wrappers/cpp/document.cpp
  internal/wrappers/cpp/kuzzle.cpp
  internal/wrappers/headers/exceptions.hpp
Labels: changelog:optimizations

#131 Index controller
  index/create.go
  index/create_test.go
  index/delete.go
  index/delete_test.go
  index/exists.go
  index/exists_test.go
  index/getAutoRefresh.go
  index/getAutoRefresh_test.go
  index/index.go
  index/list.go
  index/list_test.go
  index/mDelete.go
  index/mDelete_test.go
  index/refresh.go
  index/refreshInternal.go
  index/refreshInternal_test.go
  index/refresh_test.go
  index/setAutoRefresh.go
  index/setAutoRefresh_test.go
  internal/wrappers/cgo/kuzzle/index.go
  internal/wrappers/cgo/kuzzle/root_api.go
  internal/wrappers/cpp/index.cpp
  internal/wrappers/cpp/kuzzle.cpp
  internal/wrappers/headers/document.hpp
  internal/wrappers/headers/index.hpp
  internal/wrappers/headers/kuzzle.hpp
  internal/wrappers/headers/kuzzlesdk.h
  internal/wrappers/kcore.i
  internal/wrappers/templates/java/core.i
  kuzzle/create_index.go
  kuzzle/refresh_index.go
  kuzzle/refresh_index_test.go
  kuzzle/set_auto_refresh.go
  kuzzle/set_auto_refresh_test.go
  test.sh
Labels: changelog:breaking-changes

#135 Document controller
  document/count.go
  document/count_test.go
  document/create.go
  document/createOrReplace.go
  document/createOrReplace_test.go
  document/create_test.go
  document/delete.go
  document/deleteByQuery.go
  document/deleteByQuery_test.go
  document/delete_test.go
  document/document.go
  document/exists.go
  document/exists_test.go
  document/get.go
  document/get_test.go
  document/mCreate.go
  document/mCreateOrReplace.go
  document/mCreateOrReplace_test.go
  document/mCreate_test.go
  document/mDelete.go
  document/mDelete_test.go
  document/mGet.go
  document/mGet_test.go
  document/mReplace.go
  document/mReplace_test.go
  document/mUpdate.go
  document/mUpdate_test.go
  document/replace.go
  document/replace_test.go
  document/search.go
  document/search_test.go
  document/update.go
  document/update_test.go
  document/validate.go
  document/validate_test.go
  internal/wrappers/cgo/kuzzle/destructors.go
  internal/wrappers/cgo/kuzzle/document.go
  internal/wrappers/cgo/kuzzle/errors.go
  internal/wrappers/cgo/kuzzle/kuzzle.go
  internal/wrappers/cpp/document.cpp
  internal/wrappers/cpp/kuzzle.cpp
  internal/wrappers/headers/document.hpp
  internal/wrappers/headers/kuzzle.hpp
  internal/wrappers/headers/kuzzlesdk.h
  internal/wrappers/kcore.i
  internal/wrappers/templates/java/core.i
  kuzzle/kuzzle.go
  test.sh
Labels: changelog:breaking-changes

#140 Add query options argument in all Go/CGO/C++ functions
  index/create.go
  index/create_test.go
  index/delete.go
  index/delete_test.go
  index/exists.go
  index/exists_test.go
  index/getAutoRefresh.go
  index/getAutoRefresh_test.go
  index/list.go
  index/list_test.go
  index/mDelete.go
  index/mDelete_test.go
  index/refresh.go
  index/refreshInternal.go
  index/refreshInternal_test.go
  index/refresh_test.go
  index/setAutoRefresh.go
  index/setAutoRefresh_test.go
  internal/wrappers/cgo/kuzzle/index.go
  internal/wrappers/cpp/index.cpp
  internal/wrappers/headers/index.hpp
Labels: bug
