Repository kuzzleio/sdk-go, pull requests merged in 2018-10, with the labels that each got.

#207 fix body set as string
  document/deleteByQuery.go
  document/deleteByQuery_test.go
  realtime/validate.go
  realtime/validate_test.go
Labels: changelog:bug-fixes

#208 document.mCreatexx - take an array of documents
  document/mCreate.go
  document/mCreateOrReplace.go
  document/mCreateOrReplace_test.go
  document/mCreate_test.go
Labels: changelog:enhancements

#210 Document.m create/update array input
  document/mReplace.go
  document/mReplace_test.go
  document/mUpdate.go
  document/mUpdate_test.go
Labels: changelog:enhancements

#209 add includeTrash to query options
  document/count.go
  document/get.go
  document/mGet.go
  document/mGet_test.go
  document/search.go
  types/kuzzle_request.go
  types/query_options.go
Labels: changelog:enhancements

#211 KZL-547 - Update validateSpecifications signature to take index and collection
  collection/update_specifications.go
  collection/validate_specifications.go
  collection/validate_specifications_test.go
Labels: changelog:enhancements

#215 [bugfix] Fix all bugs introduced by force merge
  collection/update_specifications.go
  collection/validate_specifications.go
  types/validation_response.go
Labels: blocked, changelog:bug-fixes

#213 document.DeleteByQuery - return the array of ids
  document/deleteByQuery.go
Labels: changelog:enhancements

#214 readme - provide full sample
  README.md
Labels: changelog:enhancements

#216 Make websocket public
  protocol/websocket/web_socket.go
  protocol/websocket/web_socket_test.go
Labels: changelog:exclude

#219 Fix realtime count arguments
  realtime/count.go
  realtime/count_test.go
Labels: changelog:enhancements

#220 Remove realtime deprecated methods
  .github/pull_request_template.md
  realtime/list.go
  realtime/list_test.go
  realtime/validate.go
  realtime/validate_test.go
Labels: changelog:enhancements

#221 Use json.RawMessage for data in event listeners
  internal/mock_connection.go
  kuzzle/listener.go
  kuzzle/listener_test.go
  protocol/protocol.go
  protocol/websocket/web_socket.go
  protocol/websocket/web_socket_test.go
  realtime/subscribe.go
  types/ikuzzle.go
Labels: changelog:breaking-changes
