Repository kuzzleio/sdk-go, pull requests merged in 2018-08, with the labels that each got.

#183 add a mapping argument to existing collection.create methods
  .codepipeline/docker-compose.yml
  .gitignore
  README.md
  collection/create.go
  collection/create_test.go
  internal/wrappers/cgo/kuzzle/collection.go
  internal/wrappers/cpp/collection.cpp
  internal/wrappers/features/collection.feature
  internal/wrappers/features/documents.feature
  internal/wrappers/features/java/src/test/java/gradle/cucumber/Collectiondefs.java
  internal/wrappers/features/java/src/test/java/gradle/cucumber/Documentdefs.java
  internal/wrappers/features/step_defs_cpp/collection-steps.cpp
  internal/wrappers/headers/collection.hpp
  internal/wrappers/templates/java/typemap.i
Labels: changelog:enhancements

#184 Wrap Document controller for Android SDK
  .travis.yml
  internal/wrappers/cpp/document.cpp
  internal/wrappers/features/java/src/test/java/gradle/cucumber/Documentdefs.java
  internal/wrappers/features/step_defs_cpp/document-steps.cpp
  internal/wrappers/headers/document.hpp
  internal/wrappers/headers/listeners.hpp
  internal/wrappers/templates/android/core.i
  internal/wrappers/templates/android/json_wrap/document.i
  internal/wrappers/templates/android/kcore.i
  internal/wrappers/templates/android/typemap.i
Labels: changelog:new-features

#185 Wrap Auth controller for Android SDK
  internal/wrappers/templates/android/core.i
  internal/wrappers/templates/android/json_wrap/auth.i
Labels: changelog:new-features

#188 Wrap Collection controller for Android SDK
  internal/wrappers/templates/android/core.i
  internal/wrappers/templates/android/json_wrap/collection.i
  internal/wrappers/templates/android/typemap.i
Labels: changelog:new-features

#189 Wrap Server controller for Android SDK
  internal/wrappers/templates/android/core.i
  internal/wrappers/templates/android/json_wrap/server.i
  internal/wrappers/templates/android/typemap.i
  internal/wrappers/templates/java/core.i
Labels: changelog:new-features

#190 Add queryOptions when needed on Realtime controller's methods
  internal/wrappers/cgo/kuzzle/realtime.go
  internal/wrappers/cpp/realtime.cpp
  internal/wrappers/headers/realtime.hpp
  realtime/count.go
  realtime/count_test.go
  realtime/join.go
  realtime/join_test.go
  realtime/list.go
  realtime/list_test.go
  realtime/publish.go
  realtime/publish_test.go
  realtime/unsubscribe.go
  realtime/unsubscribe_test.go
  realtime/validate.go
  realtime/validate_test.go
Labels: changelog:bug-fixes

#192 Throw only possible exception in controller Index, Collection and Kuzzle object
  internal/wrappers/cpp/collection.cpp
  internal/wrappers/cpp/index.cpp
  internal/wrappers/cpp/kuzzle.cpp
  internal/wrappers/headers/collection.hpp
  internal/wrappers/headers/exceptions.hpp
  internal/wrappers/headers/index.hpp
  internal/wrappers/headers/kuzzle.hpp
Labels: changelog:enhancements

#187 [KZL-372] Add namespace kuzzleio for C structs
  internal/wrappers/Makefile
  internal/wrappers/cgo/kuzzle/auth.go
  internal/wrappers/cgo/kuzzle/c_to_go.go
  internal/wrappers/cgo/kuzzle/collection.go
  internal/wrappers/cgo/kuzzle/destructors.go
  internal/wrappers/cgo/kuzzle/document.go
  internal/wrappers/cgo/kuzzle/go_to_c.go
  internal/wrappers/cgo/kuzzle/index.go
  internal/wrappers/cgo/kuzzle/kuzzle.go
  internal/wrappers/cgo/kuzzle/realtime.go
  internal/wrappers/cgo/kuzzle/security.go
  internal/wrappers/cgo/kuzzle/server.go
  internal/wrappers/headers/kuzzlesdk.h
  internal/wrappers/headers/sdk_wrappers_internal.h
  internal/wrappers/templates/java/common.i
Labels: changelog:enhancements

#194 [Fix] Change some char* to const char*
  internal/wrappers/headers/exceptions.hpp
  internal/wrappers/headers/kuzzlesdk.h
  internal/wrappers/templates/java/typemap.i
Labels: changelog:enhancements

#191 Wrap Realtime controller for Android SDK
  internal/wrappers/templates/android/core.i
  internal/wrappers/templates/android/json_wrap/realtime.i
Labels: changelog:new-features

#195 Wrap Listeners for android
  internal/wrappers/features/step_defs_cpp/steps.hpp
  internal/wrappers/headers/listeners.hpp
  internal/wrappers/templates/android/core.i
  internal/wrappers/templates/android/json_wrap/listeners.i
Labels: changelog:enhancements

#197 Remove autoconnect
  .gitignore
  internal/wrappers/cgo/kuzzle/destructors.go
  internal/wrappers/cgo/kuzzle/kuzzle.go
  internal/wrappers/cgo/kuzzle/options.go
  internal/wrappers/cpp/kuzzle.cpp
  internal/wrappers/features/java/src/test/java/gradle/cucumber/Documentdefs.java
  internal/wrappers/features/step_defs_cpp/kuzzle-sdk-steps.cpp
  internal/wrappers/headers/kuzzle.hpp
  internal/wrappers/headers/kuzzlesdk.h
  internal/wrappers/templates/java/common.i
  internal/wrappers/templates/java/javadoc/kuzzle.i
  kuzzle/kuzzle.go
  kuzzle/kuzzle_test.go
  types/options.go
Labels: changelog:bug-fixes
