Repository kuzzleio/sdk-go, pull requests merged in 2018-11, with the labels that each got.

#222 Fix realtime:count body argument
  realtime/count.go
Labels: changelog:bug-fixes

#225 Kzl 832 document count body optional
  document/count.go
  document/count_test.go
Labels: changelog:enhancements

#226 [fix] Wrong route called in server.GetStats()
  server/getStats.go
  server/getStats_test.go
Labels: changelog:bug-fixes

#228 Rename KuzzleNotification and NotificationResult
  internal/mock_connection.go
  internal/mock_room.go
  kuzzle/kuzzle.go
  protocol/protocol.go
  protocol/websocket/web_socket.go
  realtime/subscribe.go
  realtime/subscribe_test.go
  types/ikuzzle.go
  types/kuzzle_response.go
  types/query_object.go
  types/room.go
Labels: changelog:breaking-changes

#230 Check if a channel is not nil before closing it in websocket
  protocol/websocket/web_socket.go
Labels: changelog:bug-fixes

#229 Add query parameter to collection.searchSpecifications
  collection/search_specifications.go
  collection/search_specifications_test.go
Labels: changelog:bug-fixes

#231 Fix cancelSubs
  protocol/websocket/web_socket.go
Labels: changelog:bug-fixes
