Repository kuzzleio/sdk-go, pull requests merged in 2019-08, with the labels that each got.

#247 Merge new documentation framework
  .doc/1/.vuepress
  .doc/doc.sh
  .gitignore
  .travis.yml
  package.json
Labels: do not merge

#248 Merge new documentation framework
  .doc/2/.vuepress
  .doc/doc.sh
  .gitignore
  .travis.yml
  kuzzle/query.go
  kuzzle/query_test.go
  package.json
  types/kuzzle_request.go
Labels: do not merge

#249 [hotfix] Try to reconnect if the state is not errored
  .travis.yml
  kuzzle/kuzzle.go
  kuzzle/query_test.go
  protocol/websocket/web_socket.go
Labels: changelog:bug-fixes

#250 Hotfix report
  .travis.yml
  kuzzle/kuzzle.go
  kuzzle/query_test.go
  protocol/websocket/web_socket.go
Labels: changelog:bug-fixes

#251 Remove listener when NetworkError is catched
  kuzzle/kuzzle.go
  kuzzle/query_test.go
Labels: changelog:bug-fixes

#254 Clean and optimize CI
  .travis.yml
Labels: changelog:exclude
