Repository kuzzleio/sdk-go, pull requests merged in 2020-10, with the labels that each got.

#260 Allow connecting to Kuzzle v2
  .doc/2/controllers/realtime/subscribe/snippets/user-notifications.go
  go.mod
  go.sum
  kuzzle/kuzzle.go
  kuzzle/query.go
  kuzzle/query_test.go
Labels: 3.x, changelog:new-features

#269 Use google/uuid library (SDK Go v2)
  .doc/2/essentials/getting-started/index.md
  .travis.yml
  README.md
  go.mod
  go.sum
  kuzzle/query.go
Labels: 2.x, changelog:enhancements

#268 Use google/uuid
  .ci/doc/docker-compose.yml
  .doc/doc.sh
  .travis.yml
  go.mod
  go.sum
  kuzzle/query.go
  package.json
Labels: 3.x, changelog:enhancements
